### ISSUE TITLE
Confused about learn_color

### ISSUE THREAD

**Issue by chx125ck** [yifita/DSS#13]
When I set learn color to be true in the config file, the resulting pointcloud has color that seems like random noise. When printing out the "color" in get_point_cloud in point_modeling.py, the value seems to be initialized to 1 at the first loop, but quickly goes to random numbers later (including negative values).  img_pred generated by calling self.model(...) in trainer.py also seems to have very weird results.

**Comment by lxxue** [comment]
Is the `lighting` set to `default` according to [this comment](https://github.com/yifita/DSS/blob/ce1151b27556a7e2aac18aea2a30ed97f792bb4d/configs/default.yaml#L33-L36)?

**Comment by chx125ck** [comment]
I've set the lighting to default and learn_normal to be false, but there seems to be no difference

**Comment by chx125ck** [comment]
I changed lighting to default and set learn_normal to false but there seems to be no difference

**Comment by chx125ck** [comment]
It seems to be working now, thank you.
I'm still confused by the comment though. When it says use ground truth lighting, does that mean using the light matrices provided in the dicts, in that case why should learn_color be false? With default the comment says it is using the white ambient light, does it mean comparing the model shaded with only white ambient light with reference images rendered with different light sources to compute loss?

**Comment by lxxue** [comment]
Hi, sorry for the previous reply. I checked the code and I am not sure about changing this `lighting` from `from_data` to `default` would change anything (didn't find relevant code in the repo).

I did three experiments: 
1. with `learn_normal=true; learn_color=false` (the `dss.yml`);
2. with `learn_normal=false; learn_color=true`
3. with `learn_normal=true; learn_color=true`

It seems that all experiments have visually similar results, though they have different loss values. exp1 has a loss ~0.6, exp2 ~0.8 and exp3 ~1.0 after 10 minutes. 

My feeling is, the `learn_color` and the `learn_normal` cannot be set to `true` at the same time. It will be a ill-posed problem as a point can have a correct pixel color by either changing normal or changing its point color.

What do you mean by "the resulting pointcloud has color that seems like random noise"? Could you show some visualizations?
