### ISSUE TITLE
RuntimeError: Tensors must have same number of dimensions: got 4 and 5

### ISSUE THREAD

**Issue by pbonazzi** [yifita/DSS#19]
I have run into the following error when running `scripts/create_mvr_data_from_mesh.py` for the first time 

```
`  File "scripts/create_mvr_data_from_mesh.py", line 207, in <module>
    images = renderer.shader(fragments, meshes_batch, lights=lights, cameras=cams)
  File "/home/mengqi/.conda/envs/pytorch3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mengqi/.conda/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 376, in forward
    images = hard_rgb_blend(colors, fragments, blend_params)
  File "/home/mengqi/.conda/envs/pytorch3d/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 84, in hard_rgb_blend
    return torch.cat([pixel_colors, alpha], dim=-1)  # (N, H, W, 4)
RuntimeError: Tensors must have same number of dimensions: got 4 and 5`
```

As you can see the error is raised at line 206 of the script and is caused by this call: 
`images = renderer.shader(fragments, meshes_batch, lights=lights, cameras=cams)`

Can you help me with this ?

**Version**
Python: 3.8
Pytorch: 1.6
Pytorch3D : 0.6.1

**System**
System='Linux'
release='4.15.0-188-generic'
version='#199-Ubuntu SMP Wed Jun 15 20:42:56 UTC 2022'
machine='x86_64'

**Note**
In the `README.md` file you say to run `external/prefix` , but I could only find `external/prefix_sum`. 
I have successfully run all the `setup.py` scripts.

**Comment by lxxue** [comment]
Hi, this is probably a `pytorch3d` version problem. We were working with an old version, and the new version is incompatible. I update the installation part in the [`fix/install`](https://github.com/yifita/DSS/tree/fix/install) branch. Could you check it out and create the environment again to see if you still have an issue? Things work fine on my side with this new installation.

**Comment by pbonazzi** [comment]
Well done , I have already managed to solve it on my own , by tracing back the problem in pytorch3d library . 
I will try the new installation instructions later .

**Comment by pbonazzi** [comment]
It works like a charm with #21
