### ISSUE TITLE
Got errors when compiling pytorch_points

### ISSUE THREAD

**Issue by daihengming** [yifita/DSS#2]
Hi,
I am trying compiling the pytorch_points module,but got an error:
"pytorch_points/_ext/torch_batch_svd.cpp:39:16: error: ‘TORCH_CHECK’ was not declared in this scope"
Could you please give me some help?

**Comment by yifita** [comment]
Hi, my apologies, the submodule was pointed to a later version of pytorch_points which uses pytorch 1.2.
I've corrected this and the requirements.txt is now set to pytorch=1.1.0
