### ISSUE TITLE
Visualization of the results 

### ISSUE THREAD

**Issue by pbonazzi** [yifita/DSS#24]
Hi , I have a couple of questions on the results I am getting during training . 

1) The directory `val` contains `best.ply` which if visualized with open3d with the following code, is showing an empty view. 

```
import open3d as o3d
path="best.ply"
textured_mesh = o3d.io.read_point_cloud(path)
o3d.visualization.draw_geometries([textured_mesh])
```

2) I can see how the model trains using tensorboard . And I have noticed there are points surrounding the point cloud , is this expected ?

3) The directory `vis` is  empty. Why ? 

4) In addition, how can I get the final mesh (the grey one you show in the paper) ? 

5) Finally, does the model handle texture in some way ?

**Comment by lxxue** [comment]
1. The optimized points are saved in `best.ply`. I can visualize the point cloud in meshlab. Probably you need to check how `open3d` visualizes a point cloud.

2. This is quite common to me. Some points will be pushed to the empty space and stay there. 

3. The visualization is put in `tensorboard` now. You can check `trainer.visualize` function for more details and tweak yourself if you want to visualize other stuff.

4. I am not sure how the mesh was generated in the paper. I think you can use the screened Poisson reconstruction method to get a mesh from the point cloud and the normals.

5. I think you can render textured images by changing some codes here:
https://github.com/yifita/DSS/blob/97d4bfe73ad054197f604c4e3f759e0f90745696/scripts/create_mvr_data_from_mesh.py#L128-L129

**Comment by pbonazzi** [comment]
Amazing support thanks !
