### ISSUE TITLE
Reproduce Results in Fig. 3

### ISSUE THREAD

**Issue by pbonazzi** [yifita/DSS#26]
Hi I would like to reproduce results showed in Fig.3 of the paper ? 

Could you give me a link to the mesh and the necessary config information to reproduce the results ?

Thanks !

**Comment by lxxue** [comment]
You can find the mesh [here](http://graphics.stanford.edu/data/3Dscanrep/). Unfortunately, I don't have the config but I guess you can start from the one provided and do some tweaks accordingly. The implementation of the repo is not the same as the original paper so probably you cannot reproduce the exact same result.

**Comment by pbonazzi** [comment]
I cannot find the same buddha mesh in the link you send me . About the implementation .. are the rendered images of the normals and depth values taken after splatting or simply the result of the `scripts/create_mvr_data_from_mesh` ?

**Comment by lxxue** [comment]
Sorry, you can find the correct mesh in the [training split of Sketchfab dataset](https://github.com/yifita/3PU#sketchfab-dataset).

For the second question, I think the results are rendered after splatting
